import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { cancelAppointmentAction, checkInAction, completePickupAction, correctFulfillmentAction, markNoShowAction, releaseReservationAction, reserveAppointmentAction, rescheduleAction } from "@/domains/pickups/actions";
import { getAppointmentDetail } from "@/domains/pickups/queries";
import { can, requireOrganizationContext } from "@/lib/auth/access";

export default async function AppointmentDetailPage({ params, searchParams }: { params: Promise<{ organizationSlug: string; appointmentId: string }>; searchParams: Promise<{ conflicts?: string }> }) {
  const { organizationSlug, appointmentId } = await params;
  const { conflicts } = await searchParams;
  const context = await requireOrganizationContext(organizationSlug);
  if (!can(context.effectivePermissions, "appointment.view")) notFound();
  const organizationId = context.access.organization.id;
  const detail = await getAppointmentDetail(organizationId, appointmentId);
  if (!detail || !context.access.locations.some((location) => location.id === detail.appointment.pantry_location_id)) notFound();
  const { appointment, allocationLines, reservationRows, fulfillmentRows, history, preferences } = detail;
  const permissions = context.effectivePermissions;
  const activeReservation = reservationRows.find((row) => ["active", "partially_fulfilled"].includes(row.reservation_status));
  const mayFulfill = can(permissions, "pickup.complete") && ["arrived", "partially_completed"].includes(appointment.status) && Boolean(activeReservation);

  return <div className="grid gap-10">
    <PageHeader eyebrow="Pickup appointment" title={`${appointment.appointment_number} · ${appointment.household_name}`} description={`${new Date(appointment.scheduled_start_at).toLocaleString()} · ${appointment.appointment_type.replaceAll("_", " ")}`} actions={<Link className="inline-flex min-h-11 items-center border border-[var(--ink)] px-4 text-sm font-semibold" href={`/app/${organizationSlug}/households/${appointment.household_id}`}>Open household</Link>} />
    {conflicts ? <p className="border-l-4 border-[var(--signal)] bg-white p-4 text-sm">Some optional package lines could not be fully reserved. Review reservation rows before fulfillment.</p> : null}
    <section className="grid gap-4 lg:grid-cols-3"><article className="border border-[var(--rule)] bg-white p-5"><p className="text-xs text-[var(--muted)]">Status</p><div className="mt-3"><StatusBadge status={appointment.status} /></div>{appointment.checked_in_at ? <p className="mt-3 text-sm">Checked in {new Date(appointment.checked_in_at).toLocaleString()}</p> : null}</article><article className="border border-[var(--rule)] bg-white p-5"><p className="text-xs text-[var(--muted)]">Package</p><p className="mt-3 font-semibold">{appointment.package_name ?? "Schedule only"}</p><p className="mt-2 text-sm text-[var(--muted)]">Household size snapshot: {appointment.household_size_snapshot}</p></article><article className="border border-[var(--rule)] bg-white p-5"><p className="text-xs text-[var(--muted)]">Alerts</p><ul className="mt-3 grid gap-1 text-sm">{preferences.length ? preferences.map((preference) => <li key={`${preference.preferenceType}-${preference.displayLabel}`}>{preference.displayLabel} · {preference.severity}</li>) : <li>No active preferences.</li>}</ul></article></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Allocation</h2><ul className="mt-4 grid gap-2 text-sm">{allocationLines.length ? allocationLines.map((line) => <li key={line.id}>{line.item_name ?? line.category_name ?? "Optional item"} · {line.requested_base_quantity} {line.base_unit ?? ""} · {line.is_required ? "required" : "optional"}</li>) : <li className="text-[var(--muted)]">No package allocation.</li>}</ul></article><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Reservation</h2><ul className="mt-4 grid gap-2 text-sm">{reservationRows.length ? reservationRows.map((row, index) => <li key={`${row.line_id}-${row.lot_id ?? index}`}><strong>{row.item_name}</strong> · reserved {row.reserved} / requested {row.requested} {row.base_unit}{row.lot_code ? ` · lot ${row.lot_code}` : ""}<br /><span className="text-[var(--muted)]">{row.reservation_status}{row.expires_at ? ` · expires ${new Date(row.expires_at).toLocaleString()}` : ""}</span></li>) : <li className="text-[var(--muted)]">No reservation yet.</li>}</ul></article></section>
    <section className="grid gap-4 lg:grid-cols-3">
      {can(permissions, "appointment.check_in") && ["scheduled", "confirmed"].includes(appointment.status) ? <ActionForm action={checkInAction.bind(null, organizationId, organizationSlug, appointmentId)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Check in</h2><p className="mt-2 text-sm text-[var(--muted)]">Marks the household as arrived; it does not change inventory.</p><SubmitButton pendingLabel="Checking in…" className="mt-5">Check in</SubmitButton></ActionForm> : null}
      {can(permissions, "reservation.create") && !activeReservation && ["scheduled", "confirmed", "arrived"].includes(appointment.status) ? <ActionForm action={reserveAppointmentAction.bind(null, organizationId, organizationSlug, appointmentId)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Reserve inventory</h2><p className="mt-2 text-sm text-[var(--muted)]">Uses FEFO and leaves physical stock unchanged.</p><SubmitButton pendingLabel="Reserving…" className="mt-5">Reserve package</SubmitButton></ActionForm> : null}
      {activeReservation && can(permissions, "reservation.release") ? <ActionForm action={releaseReservationAction.bind(null, organizationId, organizationSlug, activeReservation.reservation_id, appointmentId)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Release reservation</h2><Field className="mt-4" label="Reason" name="reason" required /><SubmitButton pendingLabel="Releasing…" className="mt-4">Release inventory</SubmitButton></ActionForm> : null}
    </section>
    {mayFulfill ? <section className="border border-[var(--rule)] bg-white p-6"><h2 className="text-xl font-semibold">Complete pickup</h2><p className="mt-2 text-sm text-[var(--muted)]">Only enter quantities physically handed out. Completion posts immutable pickup-fulfillment ledger entries.</p><ActionForm action={completePickupAction.bind(null, organizationId, organizationSlug, appointmentId)} className="mt-5 grid gap-4"><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} /><input type="hidden" name="lineCount" value={reservationRows.length} />{reservationRows.map((row, index) => <div key={`${row.line_id}-${row.lot_id ?? index}`} className="grid gap-3 border-b border-[var(--rule)] pb-3 sm:grid-cols-2"><input type="hidden" name={`line-${index}-reservationLineId`} value={row.line_id} /><input type="hidden" name={`line-${index}-lotId`} value={row.lot_id ?? ""} /><Field label={`${row.item_name}${row.lot_code ? ` · ${row.lot_code}` : ""}`} name={`line-${index}-quantity`} type="number" min="0" step="0.000001" max={row.lot_reserved ?? row.reserved} defaultValue={row.lot_reserved ?? row.reserved} disabled={!row.lot_id} hint={`${row.base_unit} reserved`} /></div>)}<TextAreaField label="Fulfillment notes" name="notes" maxLength={280} /><SubmitButton pendingLabel="Posting pickup…">Complete pickup</SubmitButton></ActionForm></section> : null}
    <section className="grid gap-4 lg:grid-cols-3">
      {can(permissions, "appointment.reschedule") && ["scheduled", "confirmed", "arrived"].includes(appointment.status) ? <ActionForm action={rescheduleAction.bind(null, organizationId, organizationSlug)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Reschedule</h2><input type="hidden" name="appointmentId" value={appointmentId} /><Field className="mt-4" label="Date" name="date" type="date" defaultValue={appointment.scheduled_start_at.slice(0, 10)} required /><Field className="mt-3" label="Start" name="startTime" type="time" defaultValue={appointment.scheduled_start_at.slice(11, 16)} required /><Field className="mt-3" label="End" name="endTime" type="time" defaultValue={appointment.scheduled_end_at.slice(11, 16)} required /><SubmitButton pendingLabel="Rescheduling…" className="mt-4">Reschedule</SubmitButton></ActionForm> : null}
      {can(permissions, "appointment.cancel") && ["scheduled", "confirmed", "arrived"].includes(appointment.status) ? <ActionForm action={cancelAppointmentAction.bind(null, organizationId, organizationSlug, appointmentId)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Cancel</h2><Field className="mt-4" label="Reason" name="reason" required /><SubmitButton pendingLabel="Cancelling…" className="mt-4">Cancel appointment</SubmitButton></ActionForm> : null}
      {can(permissions, "appointment.mark_no_show") && ["scheduled", "confirmed", "arrived"].includes(appointment.status) ? <ActionForm action={markNoShowAction.bind(null, organizationId, organizationSlug, appointmentId)} className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">No-show</h2><Field className="mt-4" label="Note" name="reason" required /><SubmitButton pendingLabel="Updating…" className="mt-4">Mark no-show</SubmitButton></ActionForm> : null}
    </section>
    {can(permissions, "pickup.correct") && fulfillmentRows.filter((row) => row.status === "completed").map((fulfillment) => <ActionForm key={fulfillment.id} action={correctFulfillmentAction.bind(null, organizationId, organizationSlug, fulfillment.id, appointmentId)} className="border border-[var(--signal)] bg-white p-5"><h2 className="text-lg font-semibold">Correct fulfillment</h2><p className="mt-2 text-sm text-[var(--muted)]">Posts reversing ledger transactions; completed records remain immutable.</p><Field className="mt-4" label="Correction reason" name="reason" required /><SubmitButton pendingLabel="Correcting…" className="mt-4">Correct fulfillment</SubmitButton></ActionForm>)}
    <section className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Status history</h2><ul className="mt-4 grid gap-2 text-sm">{history.map((entry) => <li key={entry.id}>{entry.fromStatus ?? "created"} → {entry.toStatus} · {entry.changedAt.toLocaleString()}</li>)}</ul></section>
  </div>;
}
