import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { correctTransactionAction, decideAdjustmentAction, submitAdjustmentAction } from "@/domains/inventory/operations-actions";
import { listAdjustmentRequests, listOperationalChoices } from "@/domains/inventory/operations-queries";

export default async function AdjustmentsPage({ params }: { params: Promise<{ organizationSlug: string }> }) {
  const { organizationSlug } = await params; const context = await requireOrganizationContext(organizationSlug); if (!can(context.effectivePermissions, "inventory.view")) notFound(); const location = context.activeLocation;
  if (!location) return <PageHeader eyebrow="Inventory controls" title="Adjustments" description="Select a pantry location." />; const organizationId = context.access.organization.id;
  const [requests, choices] = await Promise.all([listAdjustmentRequests(organizationId, location.id), listOperationalChoices(organizationId, location.id)]);
  return <div className="grid gap-10"><PageHeader eyebrow="Inventory controls" title="Adjustments" description="Normal adjustments post immediately. High-impact changes require a separate authorized approver." />
    {can(context.effectivePermissions, "inventory.adjust") ? <section className="border bg-white p-6"><h2 className="text-xl font-semibold">New adjustment request</h2><ActionForm action={submitAdjustmentAction.bind(null, organizationId, organizationSlug)} className="mt-4 grid gap-4 md:grid-cols-2"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{choices.lots.map((l) => <option key={l.id} value={l.id}>{l.item_name} · {l.lot_code ?? "unlabeled"} · {l.available_quantity} {l.base_unit} available</option>)}</SelectField><SelectField label="Direction" name="direction"><option value="positive">Increase</option><option value="negative">Decrease</option></SelectField><Field label="Quantity" name="quantity" required inputMode="decimal" /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><Field label="Reason code" name="reasonCode" required placeholder="count_variance" /><TextAreaField label="Reason" name="reason" required /><SubmitButton>Submit adjustment</SubmitButton></ActionForm></section> : null}
    {can(context.effectivePermissions, "inventory.correct") ? <section className="border bg-white p-6"><h2 className="text-xl font-semibold">Correct posted transaction</h2><p className="mt-2 text-sm text-[var(--muted)]">The original remains immutable. Correction appends an exact reversal and a replacement.</p><ActionForm action={correctTransactionAction.bind(null, organizationId, organizationSlug)} className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Transaction ID" name="transactionId" required /><SelectField label="Replacement direction" name="direction"><option value="positive">Increase</option><option value="negative">Decrease</option></SelectField><Field label="Replacement quantity" name="quantity" required /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><Field label="Reason code" name="reasonCode" required placeholder="receiving_correction" /><TextAreaField label="Correction reason" name="reason" required /><SubmitButton>Reverse and replace</SubmitButton></ActionForm></section> : null}
    <section className="grid gap-4"><h2 className="text-2xl font-semibold">Request history</h2>{requests.map((row) => <article key={row.id} className="grid gap-3 border bg-white p-5 lg:grid-cols-[1fr_auto]"><div><p className="font-semibold">{row.item_name} · {row.lot_code ?? "unlabeled lot"}</p><p className="mt-1 text-sm text-[var(--muted)]">{row.direction} {row.normalized_base_quantity} · {row.risk} risk · {row.status}</p><p className="mt-2 text-sm">{row.reason}</p></div>{row.status === "submitted" && can(context.effectivePermissions, "inventory.adjust_large") ? <div className="grid gap-2 sm:grid-cols-2"><ActionForm action={decideAdjustmentAction.bind(null, organizationId, organizationSlug, row.id, "approve")}><Field label="Approval reason" name="reason" required /><SubmitButton>Approve</SubmitButton></ActionForm><ActionForm action={decideAdjustmentAction.bind(null, organizationId, organizationSlug, row.id, "reject")}><Field label="Rejection reason" name="reason" required /><SubmitButton>Reject</SubmitButton></ActionForm></div> : null}</article>)}</section>
  </div>;
}
