import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { conditionRemovalAction, createRecallAction, quarantineAction, resolveRecallAction } from "@/domains/inventory/operations-actions";
import { listConditionEvents, listOperationalChoices, listRecalls } from "@/domains/inventory/operations-queries";

export default async function ConditionsPage({ params }: { params: Promise<{ organizationSlug: string }> }) {
  const { organizationSlug } = await params; const context = await requireOrganizationContext(organizationSlug); if (!can(context.effectivePermissions, "inventory.view")) notFound(); const location = context.activeLocation;
  if (!location) return <PageHeader eyebrow="Inventory controls" title="Condition and holds" description="Select a pantry location." />; const organizationId = context.access.organization.id;
  const [events, choices, recalls] = await Promise.all([listConditionEvents(organizationId, location.id), listOperationalChoices(organizationId, location.id), listRecalls(organizationId)]);
  const lotOptions = choices.lots.map((l) => <option key={l.id} value={l.id}>{l.item_name} · {l.lot_code ?? "unlabeled"} · {l.available_quantity} {l.base_unit}</option>);
  return <div className="grid gap-10"><PageHeader eyebrow="Inventory controls" title="Condition, quarantine, and recalls" description="Physical removals append ledger entries. Quarantine and recall are status-only holds that immediately reduce availability." />
    <section className="grid gap-6 xl:grid-cols-3">
      {can(context.effectivePermissions, "inventory.spoilage") ? <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Remove unusable stock</h2><ActionForm action={conditionRemovalAction.bind(null, organizationId, organizationSlug, "spoilage")} className="mt-4 grid gap-4"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><Field label="Quantity" name="quantity" required /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><TextAreaField label="Reason" name="reason" required /><SubmitButton>Record spoilage</SubmitButton></ActionForm></article> : null}
      {can(context.effectivePermissions, "inventory.damage") ? <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Record damage</h2><ActionForm action={conditionRemovalAction.bind(null, organizationId, organizationSlug, "damage")} className="mt-4 grid gap-4"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><Field label="Quantity" name="quantity" required /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><TextAreaField label="Reason" name="reason" required /><SubmitButton>Record damage</SubmitButton></ActionForm></article> : null}
      {can(context.effectivePermissions, "inventory.expiration_remove") ? <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Remove expired stock</h2><ActionForm action={conditionRemovalAction.bind(null, organizationId, organizationSlug, "expiration_removal")} className="mt-4 grid gap-4"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><Field label="Quantity" name="quantity" required /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><TextAreaField label="Reason" name="reason" required /><SubmitButton>Remove expired stock</SubmitButton></ActionForm></article> : null}
      {can(context.effectivePermissions, "inventory.quarantine") ? <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Place quarantine</h2><ActionForm action={quarantineAction.bind(null, organizationId, organizationSlug, "place")} className="mt-4 grid gap-4"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><TextAreaField label="Reason" name="reason" required /><SubmitButton>Quarantine lot</SubmitButton></ActionForm></article> : null}
      {can(context.effectivePermissions, "inventory.quarantine_release") ? <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Release quarantine</h2><ActionForm action={quarantineAction.bind(null, organizationId, organizationSlug, "release")} className="mt-4 grid gap-4"><SelectField label="Lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><TextAreaField label="Resolution" name="reason" required /><SubmitButton>Release hold</SubmitButton></ActionForm></article> : null}
      {can(context.effectivePermissions, "inventory.recall") ? <article className="border bg-white p-6 xl:col-span-3"><h2 className="text-xl font-semibold">Activate recall</h2><ActionForm action={createRecallAction.bind(null, organizationId, organizationSlug)} className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Reference code" name="referenceCode" required /><Field label="Title" name="title" required /><SelectField label="Affected lot" name="lotId" required><option value="">Select lot</option>{lotOptions}</SelectField><TextAreaField label="Recall instructions" name="description" required /><SubmitButton>Activate recall hold</SubmitButton></ActionForm></article> : null}
    </section>
    {recalls.length > 0 ? <section className="grid gap-4"><h2 className="text-2xl font-semibold">Recall register</h2>{recalls.map((recall) => <article key={recall.id} className="grid gap-3 border bg-white p-5 md:grid-cols-[1fr_auto]"><div><strong>{recall.reference_code} · {recall.title}</strong><p className="text-sm text-[var(--muted)]">{recall.status} · {recall.lot_count} affected lots</p></div>{recall.status === "active" && can(context.effectivePermissions, "inventory.recall_resolve") ? <ActionForm action={resolveRecallAction.bind(null, organizationId, organizationSlug, recall.id)} className="flex flex-wrap items-end gap-2"><Field label="Resolution" name="reason" required /><SubmitButton>Resolve recall</SubmitButton></ActionForm> : null}</article>)}</section> : null}
    <section><h2 className="text-2xl font-semibold">Condition history</h2><div className="mt-4 overflow-x-auto border bg-white"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b bg-[var(--surface)] text-left"><th className="p-3">Event</th><th className="p-3">Item / lot</th><th className="p-3">Quantity</th><th className="p-3">Reason</th><th className="p-3">Time</th></tr></thead><tbody>{events.map((e) => <tr key={e.id} className="border-b last:border-0"><td className="p-3 font-semibold">{e.event_type.replaceAll("_", " ")}</td><td className="p-3">{e.item_name} · {e.lot_code ?? "unlabeled"}</td><td className="p-3">{e.normalized_base_quantity ?? "status only"}</td><td className="p-3">{e.reason}</td><td className="p-3">{new Date(e.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
  </div>;
}
