import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { archiveMessageTemplateAction, createMessageTemplateAction, updateMessageTemplateAction } from "@/domains/messaging/actions";
import { listMessageTemplates } from "@/domains/messaging/queries";
import { can, requireOrganizationContext } from "@/lib/auth/access";

export default async function MessageTemplatesPage({ params }: { params: Promise<{ organizationSlug: string }> }) {
  const { organizationSlug } = await params; const context = await requireOrganizationContext(organizationSlug); const location = context.activeLocation;
  if (!location || !can(context.effectivePermissions, "message.template.view")) notFound();
  const organizationId = context.access.organization.id; const templates = await listMessageTemplates(context.user.id, organizationId, location.id);
  return <div className="grid gap-10"><PageHeader eyebrow="Reusable copy" title="Message templates" description="Templates support explicit {{variable_name}} placeholders. Sent messages retain an immutable body snapshot when this template later changes." />
    {can(context.effectivePermissions, "message.template.create") ? <section className="border border-[var(--rule)] bg-white p-5"><h2 className="text-xl font-semibold">Create template</h2><ActionForm action={createMessageTemplateAction.bind(null, organizationId, organizationSlug, location.id)} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Name" name="name" required maxLength={120}/><SelectField label="Type" name="templateType" defaultValue="appointment_reminder"><option value="appointment_reminder">Appointment reminder</option><option value="appointment_confirmation">Appointment confirmation</option><option value="closure_notice">Closure notice</option><option value="bulk_announcement">Bulk announcement</option><option value="help_response">Help response</option><option value="other">Other</option></SelectField><Field label="Language" name="language" defaultValue="en" required/><TextAreaField label="Message body" name="body" required maxLength={1600} className="md:col-span-2" hint="Use placeholders such as {{household_name}}, {{appointment_date}}, and {{appointment_time}}."/><SubmitButton pendingLabel="Creating…">Create template</SubmitButton></ActionForm></section> : null}
    <section className="grid gap-4">{templates.length ? templates.map((template) => <article key={template.id} className="border border-[var(--rule)] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{template.name}</h2><p className="text-sm text-[var(--muted)]">{template.template_type.replaceAll("_", " ")} · {template.language}</p></div><StatusBadge status={template.status}/></div><p className="mt-4 whitespace-pre-wrap text-sm">{template.body}</p>{template.variables.length ? <p className="mt-3 text-xs text-[var(--muted)]">Variables: {template.variables.join(", ")}</p> : null}{can(context.effectivePermissions, "message.template.update") && !template.is_system_template ? <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Edit template</summary><ActionForm action={updateMessageTemplateAction.bind(null, organizationId, organizationSlug, location.id, template.id)} className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Name" name="name" defaultValue={template.name} required/><Field label="Type" name="templateType" defaultValue={template.template_type} required/><Field label="Language" name="language" defaultValue={template.language} required/><TextAreaField label="Message body" name="body" defaultValue={template.body} required maxLength={1600} className="md:col-span-2"/><SubmitButton pendingLabel="Updating…">Update template</SubmitButton></ActionForm></details> : null}{can(context.effectivePermissions, "message.template.archive") && !template.is_system_template ? <ActionForm action={archiveMessageTemplateAction.bind(null, organizationId, organizationSlug, location.id, template.id)} className="mt-4"><SubmitButton variant="danger" pendingLabel="Archiving…">Archive</SubmitButton></ActionForm> : null}</article>) : <p className="border border-dashed border-[var(--rule)] p-6 text-sm text-[var(--muted)]">No active templates yet.</p>}</section>
  </div>;
}
