import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { receiveTransferLineAction, transferTransitionAction } from "@/domains/inventory/operations-actions";
import { getTransfer } from "@/domains/inventory/operations-queries";

export default async function TransferDetailPage({ params }: { params: Promise<{ organizationSlug: string; transferId: string }> }) {
  const { organizationSlug, transferId } = await params; const context = await requireOrganizationContext(organizationSlug); if (!can(context.effectivePermissions, "inventory.view")) notFound(); const organizationId = context.access.organization.id; const result = await getTransfer(organizationId, transferId); if (!result) notFound(); const transfer = result.transfer as Record<string, unknown>; const status = String(transfer.status);
  return <div className="grid gap-10"><PageHeader eyebrow="Inventory transfer" title={String(transfer.transfer_number)} description={`${String(transfer.source_name)} → ${String(transfer.destination_name)} · ${status.replaceAll("_", " ")}`} />
    <section className="grid gap-3">{result.lines.map((line) => <article key={String(line.id)} className="grid gap-3 border bg-white p-5 lg:grid-cols-[1fr_auto]"><div><strong>{String(line.item_name)} · {line.lot_code ? String(line.lot_code) : "unlabeled lot"}</strong><p className="text-sm text-[var(--muted)]">Requested {String(line.requested_quantity)} {String(line.requested_unit)} · dispatched {String(line.dispatched_base_quantity)} · received {String(line.received_base_quantity)} · in transit {String(line.in_transit_quantity)}</p></div>{["dispatched", "partially_received"].includes(status) && can(context.effectivePermissions, "inventory.transfer_receive") ? <ActionForm action={receiveTransferLineAction.bind(null, organizationId, organizationSlug, transferId, String(line.id))} className="flex flex-wrap items-end gap-2"><Field label="Receive quantity" name="quantity" required /><input type="hidden" name="unitId" value={String(line.requested_unit_id)} /><Field label="Discrepancy note" name="discrepancyReason" /><SubmitButton>Receive</SubmitButton></ActionForm> : null}</article>)}</section>
    <section className="flex flex-wrap gap-3">{status === "draft" && can(context.effectivePermissions, "inventory.transfer") ? <ActionForm action={transferTransitionAction.bind(null, organizationId, organizationSlug, transferId, "request")}><SubmitButton>Request approval</SubmitButton></ActionForm> : null}{status === "requested" && can(context.effectivePermissions, "inventory.transfer_approve") ? <ActionForm action={transferTransitionAction.bind(null, organizationId, organizationSlug, transferId, "approve")}><SubmitButton>Approve transfer</SubmitButton></ActionForm> : null}{status === "approved" && can(context.effectivePermissions, "inventory.transfer_dispatch") ? <ActionForm action={transferTransitionAction.bind(null, organizationId, organizationSlug, transferId, "dispatch")}><SubmitButton>Dispatch stock</SubmitButton></ActionForm> : null}{["draft", "requested", "approved"].includes(status) && can(context.effectivePermissions, "inventory.transfer_cancel") ? <ActionForm action={transferTransitionAction.bind(null, organizationId, organizationSlug, transferId, "cancel")} className="flex items-end gap-2"><Field label="Cancellation reason" name="reason" required /><SubmitButton>Cancel</SubmitButton></ActionForm> : null}{["partially_received", "received"].includes(status) && can(context.effectivePermissions, "inventory.transfer_discrepancy") ? <ActionForm action={transferTransitionAction.bind(null, organizationId, organizationSlug, transferId, "resolve")} className="grid gap-2"><TextAreaField label="Resolution" name="reason" required /><SubmitButton>Resolve discrepancy</SubmitButton></ActionForm> : null}</section>
  </div>;
}
