import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { cycleCountTransitionAction, enterCycleCountAction } from "@/domains/inventory/operations-actions";
import { getCycleCount } from "@/domains/inventory/operations-queries";

export default async function CountDetailPage({ params }: { params: Promise<{ organizationSlug: string; sessionId: string }> }) {
  const { organizationSlug, sessionId } = await params; const context = await requireOrganizationContext(organizationSlug); if (!can(context.effectivePermissions, "inventory.view")) notFound(); const organizationId = context.access.organization.id; const result = await getCycleCount(organizationId, sessionId); if (!result) notFound(); const session = result.session as Record<string, unknown>; const status = String(session.status);
  return <div className="grid gap-10"><PageHeader eyebrow="Cycle count" title={`Count ${sessionId.slice(0, 8)}`} description={`Status: ${status} · snapshot ${new Date(String(session.snapshot_at)).toLocaleString()}`} />
    <section className="grid gap-3">{result.entries.map((entry) => <article key={String(entry.id)} className="grid gap-3 border bg-white p-5 lg:grid-cols-[1fr_auto]"><div><strong>{String(entry.item_name)} · {entry.lot_code ? String(entry.lot_code) : "unlabeled lot"}</strong><p className="text-sm text-[var(--muted)]">Snapshot {String(entry.snapshot_quantity)} {String(entry.base_unit)} · counted {entry.normalized_counted_quantity === null ? "pending" : String(entry.normalized_counted_quantity)} · variance {entry.variance_quantity === null ? "—" : String(entry.variance_quantity)}</p></div>{["draft", "counting"].includes(status) && can(context.effectivePermissions, "inventory.reconcile") ? <ActionForm action={enterCycleCountAction.bind(null, organizationId, organizationSlug, sessionId, String(entry.id), String(entry.base_unit_id))} className="flex flex-wrap items-end gap-2"><Field label="Physical count" name="quantity" required inputMode="decimal" defaultValue={entry.counted_quantity === null ? "" : String(entry.counted_quantity)} /><Field label="Notes" name="notes" defaultValue={entry.notes === null ? "" : String(entry.notes)} /><SubmitButton>Save count</SubmitButton></ActionForm> : null}</article>)}</section>
    <section className="flex flex-wrap gap-3">{status === "counting" && can(context.effectivePermissions, "inventory.reconcile") ? <ActionForm action={cycleCountTransitionAction.bind(null, organizationId, organizationSlug, sessionId, "submit")}><SubmitButton>Submit count</SubmitButton></ActionForm> : null}{status === "submitted" && can(context.effectivePermissions, "inventory.reconcile_approve") ? <ActionForm action={cycleCountTransitionAction.bind(null, organizationId, organizationSlug, sessionId, "approve")}><SubmitButton>Approve count</SubmitButton></ActionForm> : null}{status === "approved" && can(context.effectivePermissions, "inventory.reconcile_approve") ? <ActionForm action={cycleCountTransitionAction.bind(null, organizationId, organizationSlug, sessionId, "reconcile")}><SubmitButton>Post reconciliation</SubmitButton></ActionForm> : null}</section>
  </div>;
}
