import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { addContactAction, addPreferenceAction, archiveHouseholdAction, recordConsentAction, updateHouseholdAction } from "@/domains/pickups/actions";
import { findDuplicateCandidates, getHousehold } from "@/domains/pickups/queries";
import { can, requireOrganizationContext } from "@/lib/auth/access";

export default async function HouseholdDetailPage({ params }: { params: Promise<{ organizationSlug: string; householdId: string }> }) {
  const { organizationSlug, householdId } = await params;
  const context = await requireOrganizationContext(organizationSlug);
  if (!can(context.effectivePermissions, "household.view_basic")) notFound();
  const permissions = context.effectivePermissions;
  const organizationId = context.access.organization.id;
  const data = await getHousehold(organizationId, householdId, { contacts: can(permissions, "household.view_contact"), sensitive: can(permissions, "household.view_sensitive") });
  if (!data) notFound();
  const duplicates = await findDuplicateCandidates(organizationId, householdId);
  const { household } = data;
  const mayUpdate = can(permissions, "household.update");

  return <div className="grid gap-10">
    <PageHeader eyebrow="Household" title={household.displayName} description={`${household.householdNumber} · size ${household.householdSize} · ${household.preferredLanguage}`} actions={<Link className="inline-flex min-h-11 items-center border border-[var(--ink)] px-4 text-sm font-semibold" href={`/app/${organizationSlug}/pickups/appointments/new`}>Schedule pickup</Link>} />
    <section className="grid gap-4 lg:grid-cols-2">
      <article className="border border-[var(--rule)] bg-white p-5"><p className="text-xs text-[var(--muted)]">Status</p><div className="mt-3"><StatusBadge status={household.status} /></div><p className="mt-5 text-sm">{household.operationalNotes ?? "No operational notes."}</p>{can(permissions, "household.view_sensitive") && household.sensitiveNotes ? <p className="mt-3 border-l-4 border-[var(--signal)] pl-3 text-sm">Sensitive: {household.sensitiveNotes}</p> : null}</article>
      <article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Duplicate review</h2>{duplicates.length ? <ul className="mt-3 grid gap-2 text-sm">{duplicates.map((item) => <li key={item.id}><Link className="font-semibold underline" href={`/app/${organizationSlug}/households/${item.id}`}>{item.display_name}</Link> · {item.reasons}</li>)}</ul> : <p className="mt-3 text-sm text-[var(--muted)]">No duplicate candidates detected.</p>}</article>
    </section>
    {mayUpdate ? <section className="border border-[var(--rule)] bg-white p-6"><h2 className="text-xl font-semibold">Update household</h2><ActionForm action={updateHouseholdAction.bind(null, organizationId, organizationSlug, householdId)} className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Household name" name="displayName" defaultValue={household.displayName} required /><Field label="Household size" name="householdSize" type="number" min="1" max="50" defaultValue={household.householdSize} required /><Field label="Adults" name="adultCount" type="number" min="0" defaultValue={household.adultCount ?? ""} /><Field label="Children" name="childCount" type="number" min="0" defaultValue={household.childCount ?? ""} /><Field label="Seniors" name="seniorCount" type="number" min="0" defaultValue={household.seniorCount ?? ""} /><Field label="Language" name="preferredLanguage" defaultValue={household.preferredLanguage} /></div><TextAreaField label="Operational notes" name="operationalNotes" defaultValue={household.operationalNotes ?? ""} /><Field label="External reference" name="externalReference" defaultValue={household.externalReference ?? ""} /><SubmitButton pendingLabel="Saving…">Save household</SubmitButton></ActionForm></section> : null}
    {can(permissions, "household.view_contact") ? <section className="grid gap-4 lg:grid-cols-2"><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Contacts</h2><ul className="mt-4 grid gap-3 text-sm">{data.contacts.map((contact) => <li key={contact.id} className="border-b border-[var(--rule)] pb-2"><strong>{contact.name}</strong> · {contact.contactType}<br />{contact.phoneNumber ?? contact.email ?? "No contact method"}</li>)}</ul>{mayUpdate ? <ActionForm action={addContactAction.bind(null, organizationId, organizationSlug)} className="mt-5 grid gap-3"><input type="hidden" name="householdId" value={householdId} /><Field label="Contact name" name="name" required /><SelectField label="Type" name="contactType" defaultValue="primary"><option value="primary">Primary</option><option value="alternate">Alternate</option><option value="emergency">Emergency</option><option value="caregiver">Caregiver</option><option value="authorized_pickup">Authorized pickup</option></SelectField><Field label="Phone" name="phoneNumber" /><Field label="Email" name="email" /><label className="text-sm"><input className="mr-2" type="checkbox" name="isAuthorizedPickup" />Authorized pickup</label><SubmitButton pendingLabel="Adding…">Add contact</SubmitButton></ActionForm> : null}</article><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">SMS consent</h2><ul className="mt-4 grid gap-2 text-sm">{data.consents.map((consent) => <li key={consent.id}>{consent.status} · {consent.phoneNormalized} · {consent.effectiveAt.toLocaleDateString()}</li>)}</ul>{can(permissions, "consent.record") ? <ActionForm action={recordConsentAction.bind(null, organizationId, organizationSlug)} className="mt-5 grid gap-3"><input type="hidden" name="householdId" value={householdId} /><Field label="Phone" name="phoneNumber" required /><SelectField label="Status" name="status" defaultValue="consented"><option value="consented">Consented</option><option value="opted_out">Opted out</option><option value="revoked">Revoked</option><option value="unknown">Unknown</option><option value="invalid_number">Invalid number</option></SelectField><SelectField label="Source" name="consentSource" defaultValue="paper_form"><option value="paper_form">Paper form</option><option value="verbal">Verbal</option><option value="administrative_correction">Administrative correction</option></SelectField><SubmitButton pendingLabel="Recording…">Record consent</SubmitButton></ActionForm> : null}</article></section> : null}
    <section className="grid gap-4 lg:grid-cols-2"><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Preferences and alerts</h2><ul className="mt-4 grid gap-2 text-sm">{data.preferences.map((preference) => <li key={`${preference.preferenceType}-${preference.displayLabel}`}>{preference.displayLabel} · {preference.severity}</li>)}</ul>{mayUpdate ? <ActionForm action={addPreferenceAction.bind(null, organizationId, organizationSlug)} className="mt-5 grid gap-3"><input type="hidden" name="householdId" value={householdId} /><SelectField label="Type" name="preferenceType" defaultValue="dietary"><option value="dietary">Dietary</option><option value="allergen">Allergen</option><option value="accessibility">Accessibility</option><option value="pickup">Pickup</option></SelectField><Field label="Code" name="valueCode" placeholder="vegetarian" required /><Field label="Label" name="displayLabel" required /><SelectField label="Severity" name="severity" defaultValue="info"><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></SelectField><SubmitButton pendingLabel="Saving…">Add preference</SubmitButton></ActionForm> : null}</article><article className="border border-[var(--rule)] bg-white p-5"><h2 className="text-lg font-semibold">Pickup history</h2><ul className="mt-4 grid gap-2 text-sm">{data.history.map((appointment) => <li key={appointment.id}><Link className="underline" href={`/app/${organizationSlug}/pickups/appointments/${appointment.id}`}>{appointment.appointmentNumber}</Link> · {appointment.status} · {appointment.scheduledStartAt.toLocaleDateString()}</li>)}</ul>{can(permissions, "household.archive") && household.status === "active" ? <ActionForm action={archiveHouseholdAction.bind(null, organizationId, organizationSlug, householdId)} className="mt-6 grid gap-3"><Field label="Archive reason" name="reason" required /><SubmitButton pendingLabel="Archiving…">Archive household</SubmitButton></ActionForm> : null}</article></section>
  </div>;
}
