import "server-only";

import { db, pool } from "@/lib/database/client";
import { hasLocationPermission } from "@/lib/database/authorization";
import { DomainError } from "@/lib/errors";
import { alertFingerprint, calculateForecast, forecastDate } from "@/domains/forecasting/policy";
import { fitAdvancedForecastModel } from "@/domains/forecasting/advanced";
import type { PoolClient } from "pg";

type Config = { id: string; lookback_7_day_weight: string; lookback_30_day_weight: string; lookback_90_day_weight: string; minimum_history_days: number; safety_stock_fixed_quantity: string; safety_stock_days: string; lead_time_days: number; forecast_horizon_days: number; shortage_warning_days: number; urgent_shortage_days: number; demand_spike_threshold: string };
type ItemRow = { id: string; name: string; category_id: string; physical: string; reserved: string; available: string; missing_expiration: string };

async function requireLocation(actorId: string, locationId: string, permission: string) {
  if (!(await hasLocationPermission(db, actorId, locationId, permission))) throw new DomainError("FORBIDDEN");
}

async function resolveConfig(client: PoolClient, organizationId: string, locationId: string, itemId?: string, categoryId?: string) {
  const result = await client.query(`select * from forecast_configurations where organization_id=$1 and is_active and archived_at is null and (scope_type='organization_default' or (pantry_location_id=$2 and scope_type='location_default') or (pantry_location_id=$2 and inventory_category_id=$3 and scope_type='category_override') or (pantry_location_id=$2 and inventory_item_id=$4 and scope_type='item_override')) order by case scope_type when 'item_override' then 1 when 'category_override' then 2 when 'location_default' then 3 else 4 end limit 1`, [organizationId, locationId, categoryId ?? null, itemId ?? null]);
  if (!result.rows[0]) throw new DomainError("FORECAST_CONFIGURATION_MISSING");
  return result.rows[0] as Config;
}

async function operatingDays(client: PoolClient, organizationId: string, locationId: string, asOf: Date, windowDays: number) {
  const end = asOf.toISOString().slice(0, 10);
  const result = await client.query(`with dates as (select d::date as day from generate_series($3::date - ($4::int || ' days')::interval,$3::date - interval '1 day',interval '1 day') d), chosen as (select d.day,coalesce(e.is_open,c.is_open,false) open from dates d left join pantry_calendar_exceptions e on e.pantry_location_id=$2 and e.date=d.day left join lateral (select is_open from pantry_operating_calendars c where c.organization_id=$1 and c.pantry_location_id=$2 and c.day_of_week=extract(dow from d.day)::int and c.effective_from<=d.day and (c.effective_to is null or c.effective_to>=d.day) order by c.effective_from desc limit 1) c on true) select count(*)::text count from chosen where open`, [organizationId, locationId, end, windowDays]);
  return Number(result.rows[0]?.count ?? 0);
}

async function writeAudit(client: PoolClient, actorId: string, organizationId: string, action: string, entityType: string, entityId: string, locationId: string, requestId: string, metadata: object = {}) {
  const membership = await client.query(`select id from organization_memberships where organization_id=$1 and user_id=$2 and status='active' and archived_at is null limit 1`, [organizationId, actorId]);
  await client.query(`insert into audit_logs(organization_id,location_id,actor_user_id,actor_membership_id,action,entity_type,entity_id,source,request_id,metadata) values($1,$2,$3,$4,$5,$6,$7,'application',$8,$9::jsonb)`, [organizationId, locationId, actorId, membership.rows[0]?.id ?? null, action, entityType, entityId, requestId, JSON.stringify(metadata)]);
}

async function upsertAlert(client: PoolClient, input: { organizationId: string; locationId: string; type: string; severity: "info"|"warning"|"critical"; title: string; summary: string; sourceId: string; details: object }) {
  const fingerprint = alertFingerprint(input.organizationId,input.locationId,input.type,input.sourceId);
  const existing = await client.query(`select id,status,severity from operational_alerts where organization_id=$1 and fingerprint=$2 for update`, [input.organizationId,fingerprint]);
  if (!existing.rows[0]) {
    const inserted = await client.query(`insert into operational_alerts(organization_id,pantry_location_id,alert_type,severity,fingerprint,title,summary,source_type,source_id,details) values($1,$2,$3,$4,$5,$6,$7,'forecast_item',$8,$9::jsonb) returning id`, [input.organizationId,input.locationId,input.type,input.severity,fingerprint,input.title,input.summary,input.sourceId,JSON.stringify(input.details)]);
    await client.query(`insert into operational_alert_events(operational_alert_id,organization_id,event_type,to_status,metadata) values($1,$2,'created','open',$3::jsonb)`, [inserted.rows[0].id,input.organizationId,JSON.stringify({ severity: input.severity })]);
    return;
  }
  const previous = existing.rows[0];
  const reopen = previous.status === "resolved" || (previous.status === "dismissed" && input.severity === "critical");
  await client.query(`update operational_alerts set severity=$2,title=$3,summary=$4,details=$5::jsonb,last_detected_at=now(),occurrence_count=occurrence_count+1,status=case when $6 then 'open'::operational_alert_status else status end,resolved_at=case when $6 then null else resolved_at end,dismissed_at=case when $6 then null else dismissed_at end,updated_at=now() where id=$1`, [previous.id,input.severity,input.title,input.summary,JSON.stringify(input.details),reopen]);
  await client.query(`insert into operational_alert_events(operational_alert_id,organization_id,event_type,from_status,to_status,metadata) values($1,$2,$3,$4,$5,$6::jsonb)`, [previous.id,input.organizationId,reopen?'reopened':'detected',previous.status,reopen?'open':previous.status,JSON.stringify({ previousSeverity: previous.severity, severity: input.severity })]);
}

export async function generateForecast(actorId: string, organizationId: string, locationId: string, requestId: string, jobId?: string) {
  await requireLocation(actorId, locationId, "forecast.recalculate");
  const client = await pool.connect();
  try {
    await client.query("begin");
    await client.query("select pg_advisory_xact_lock(hashtext($1))", [`forecast:${organizationId}:${locationId}`]);
    const asOf = new Date();
    const defaultConfig = await resolveConfig(client,organizationId,locationId);
    const advancedConfig = (await client.query<{ enabled: boolean; seasonality: unknown; causal_factors: unknown }>(`select enabled,seasonality,causal_factors from forecast_model_configs where organization_id=$1 and pantry_location_id=$2 limit 1`, [organizationId, locationId])).rows[0];
    const causalEvents = (await client.query<{ starts_on: string; ends_on: string; demand_multiplier: string }>(`select starts_on::text,ends_on::text,demand_multiplier::text from forecast_causal_events where organization_id=$1 and pantry_location_id=$2 and ends_on >= $3::date and starts_on <= $4::date`, [organizationId, locationId, asOf.toISOString().slice(0, 10), forecastDate(asOf, defaultConfig.forecast_horizon_days)])).rows.map((event) => ({ startsOn: event.starts_on, endsOn: event.ends_on, demandMultiplier: Number(event.demand_multiplier) }));
    const useAdvancedModel = Boolean(advancedConfig?.enabled);
    const horizonEnd = forecastDate(asOf,defaultConfig.forecast_horizon_days)!;
    const snapshot = (await client.query<{ id: string }>(`insert into forecast_snapshots(organization_id,pantry_location_id,calculation_version,as_of,horizon_end,source_watermark,configuration_snapshot,generated_by,job_id) values($1,$2,$3,$4,$5,(select jsonb_build_object('ledger',coalesce(max(created_at),$4)) from inventory_transactions where organization_id=$1),$6::jsonb,$7,$8) returning id`, [organizationId,locationId,useAdvancedModel ? 'v2-hybrid-seasonal-causal' : 'v1-deterministic',asOf,horizonEnd,JSON.stringify({ ...defaultConfig, advancedModel: useAdvancedModel, causalEvents }),actorId,jobId ?? null])).rows[0]!;
    const itemRows = await client.query<ItemRow>(`select i.id,i.name,i.category_id,coalesce(sum(b.physical_on_hand),0)::text physical,coalesce(sum(b.reserved_quantity),0)::text reserved,coalesce(sum(b.available_quantity),0)::text available,coalesce(sum(case when l.expiration_date is null and b.physical_on_hand>0 then b.physical_on_hand else 0 end),0)::text missing_expiration from inventory_items i left join inventory_lots l on l.inventory_item_id=i.id and l.pantry_location_id=$2 and l.archived_at is null left join inventory_lot_balances b on b.inventory_lot_id=l.id where i.organization_id=$1 and i.archived_at is null group by i.id,i.name,i.category_id order by i.name`, [organizationId,locationId]);
    const op7 = await operatingDays(client,organizationId,locationId,asOf,7), op30 = await operatingDays(client,organizationId,locationId,asOf,30), op90 = await operatingDays(client,organizationId,locationId,asOf,90);
    for (const item of itemRows.rows) {
      const config = await resolveConfig(client,organizationId,locationId,item.id,item.category_id);
      const history = await client.query<{ d7:string;d30:string;d90:string;tx_count:string }>(`select coalesce(sum(case when occurred_at >= $4::timestamptz-interval '7 days' then q else 0 end),0)::text d7,coalesce(sum(case when occurred_at >= $4::timestamptz-interval '30 days' then q else 0 end),0)::text d30,coalesce(sum(case when occurred_at >= $4::timestamptz-interval '90 days' then q else 0 end),0)::text d90,count(*)::text tx_count from (select t.occurred_at,greatest(-t.physical_delta,0) q from inventory_transactions t where t.organization_id=$1 and t.pantry_location_id=$2 and t.inventory_item_id=$3 and t.transaction_type='pickup_fulfillment' union all select r.occurred_at,-greatest(r.physical_delta,0) from inventory_transactions r join inventory_transactions original on original.id=r.reverses_transaction_id and original.transaction_type='pickup_fulfillment' where r.organization_id=$1 and r.pantry_location_id=$2 and r.inventory_item_id=$3) x`, [organizationId,locationId,item.id,asOf]);
      const dailyHistory = useAdvancedModel ? await client.query<{ day: string; quantity: string }>(`select occurred_at::date::text day, sum(greatest(-physical_delta,0))::text quantity from inventory_transactions where organization_id=$1 and pantry_location_id=$2 and inventory_item_id=$3 and transaction_type='pickup_fulfillment' and occurred_at >= $4::timestamptz-interval '365 days' group by occurred_at::date order by occurred_at::date`, [organizationId, locationId, item.id, asOf]) : null;
      const scheduled = await client.query<{ total:string;reserved:string;unreserved:string;appointments:string }>(`select coalesce(sum(al.requested_base_quantity),0)::text total,coalesce(sum(least(al.requested_base_quantity,coalesce(rl.reserved_base_quantity-rl.fulfilled_base_quantity-rl.released_base_quantity,0))),0)::text reserved,coalesce(sum(greatest(al.requested_base_quantity-coalesce(rl.reserved_base_quantity-rl.fulfilled_base_quantity-rl.released_base_quantity,0),0)),0)::text unreserved,count(distinct a.id)::text appointments from appointments a join appointment_allocations aa on aa.appointment_id=a.id join appointment_allocation_lines al on al.appointment_allocation_id=aa.id left join inventory_reservation_lines rl on rl.appointment_allocation_line_id=al.id and exists(select 1 from inventory_reservations r where r.id=rl.reservation_id and r.status in('active','partially_fulfilled')) where a.organization_id=$1 and a.pantry_location_id=$2 and al.inventory_item_id=$3 and a.status in('scheduled','confirmed','arrived') and a.scheduled_start_at >= $4 and a.scheduled_start_at < $5::date+interval '1 day'`, [organizationId,locationId,item.id,asOf,horizonEnd]);
      const incoming = await client.query<{ quantity:string }>(`select coalesce(sum(quantity),0)::text quantity from (select dl.expected_quantity*iu.factor quantity from donations d join donation_lines dl on dl.donation_id=d.id join inventory_item_units iu on iu.inventory_item_id=dl.inventory_item_id and iu.unit_id=dl.expected_unit_id and iu.is_active where d.organization_id=$1 and d.pantry_location_id=$2 and dl.inventory_item_id=$3 and d.status='receiving' and d.expected_arrival_at between $4 and $5::date+interval '1 day' union all select greatest(tl.dispatched_base_quantity-tl.received_base_quantity,0) from inventory_transfers t join inventory_transfer_lines tl on tl.transfer_id=t.id where t.organization_id=$1 and t.destination_location_id=$2 and tl.inventory_item_id=$3 and t.status in('dispatched','partially_received')) incoming`, [organizationId,locationId,item.id,asOf,horizonEnd]);
      const expiring = await client.query<{ quantity:string }>(`select coalesce(sum(b.available_quantity),0)::text quantity from inventory_lot_balances b join inventory_lots l on l.id=b.inventory_lot_id where l.organization_id=$1 and l.pantry_location_id=$2 and l.inventory_item_id=$3 and l.expiration_date between $4::date and $5::date and b.available_quantity>0`, [organizationId,locationId,item.id,asOf,horizonEnd]);
      const h=history.rows[0]!,s=scheduled.rows[0]!,inc=incoming.rows[0]!,exp=expiring.rows[0]!;
      const advancedModel = dailyHistory && dailyHistory.rows.length >= 7 ? fitAdvancedForecastModel(dailyHistory.rows.map((row) => ({ date: row.day, quantity: Number(row.quantity) })), causalEvents) : null;
      const calculated=calculateForecast({available:Number(item.available),historical:advancedModel ? { days7: advancedModel.predict(asOf) * Math.max(op7, 1), days30: advancedModel.predict(asOf) * Math.max(op30, 1), days90: advancedModel.predict(asOf) * Math.max(op90, 1), operating7: op7, operating30: op30, operating90: op90 } : {days7:Number(h.d7),days30:Number(h.d30),days90:Number(h.d90),operating7:op7,operating30:op30,operating90:op90},weights:advancedModel ? [1,0,0] : [Number(config.lookback_7_day_weight),Number(config.lookback_30_day_weight),Number(config.lookback_90_day_weight)],scheduledReserved:Number(s.reserved),scheduledUnreserved:Number(s.unreserved),confirmedIncoming:Number(inc.quantity),expiringBeforeUse:Number(exp.quantity),safetyStockDays:Number(config.safety_stock_days),safetyStockFixed:Number(config.safety_stock_fixed_quantity),leadTimeDays:config.lead_time_days,horizonDays:config.forecast_horizon_days,minimumHistoryDays:config.minimum_history_days});
      const explanation={classification:{physical:"observed",weightedDemand:advancedModel ? "hybrid_seasonal_causal_model" : "derived",shortageDate:"estimate",recommendedQuantity:"recommendation"},advancedModel:advancedModel ? {version:advancedModel.modelVersion,sampleCount:advancedModel.sampleCount,baselineDailyDemand:advancedModel.baselineDailyDemand,trendPerDay:advancedModel.trendPerDay,weekdayFactors:advancedModel.weekdayFactors,monthFactors:advancedModel.monthFactors,causalMultipliers:advancedModel.activeCausalMultipliers,confidenceScore:advancedModel.confidenceScore} : null,history:{operatingDays:[op7,op30,op90],transactions:Number(h.tx_count),normalizedWeights:calculated.normalizedWeights},scheduled:{total:Number(s.total),reserved:Number(s.reserved),unreserved:Number(s.unreserved),appointments:Number(s.appointments)},incoming:Number(inc.quantity),expiring:Number(exp.quantity),configurationId:config.id};
      await client.query(`insert into forecast_item_results(snapshot_id,organization_id,pantry_location_id,inventory_item_id,physical_on_hand,reserved_quantity,available_quantity,historical_7_quantity,historical_30_quantity,historical_90_quantity,weighted_daily_demand,scheduled_demand,scheduled_reserved,scheduled_unreserved,confirmed_incoming,expiring_before_use,safety_stock,lead_time_demand,days_of_supply,projected_shortage_date,projected_stockout_date,recommended_quantity,confidence_score,confidence_level,risk_level,explanation) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26::jsonb)`, [snapshot.id,organizationId,locationId,item.id,item.physical,item.reserved,item.available,h.d7,h.d30,h.d90,calculated.weightedDailyDemand,s.total,s.reserved,s.unreserved,inc.quantity,exp.quantity,calculated.safetyStock,calculated.leadTimeDemand,calculated.daysOfSupply,forecastDate(asOf,calculated.shortageOffset),forecastDate(asOf,calculated.stockoutOffset),calculated.recommendedQuantity,calculated.confidenceScore,calculated.confidenceLevel,calculated.riskLevel,JSON.stringify(explanation)]);
      if (calculated.confidenceLevel === "insufficient_data") await client.query(`insert into forecast_diagnostics(snapshot_id,organization_id,pantry_location_id,inventory_item_id,code,severity,message,details) values($1,$2,$3,$4,'INSUFFICIENT_HISTORY','warning','No completed pickup history is available for this item.',$5::jsonb)`,[snapshot.id,organizationId,locationId,item.id,JSON.stringify({operatingDays:op90})]);
      if (Number(item.missing_expiration)>0) await client.query(`insert into forecast_diagnostics(snapshot_id,organization_id,pantry_location_id,inventory_item_id,code,severity,message,details) values($1,$2,$3,$4,'MISSING_EXPIRATION','warning','Usable stock is missing an expiration date.',$5::jsonb)`,[snapshot.id,organizationId,locationId,item.id,JSON.stringify({quantity:Number(item.missing_expiration)})]);
      if (calculated.riskLevel !== "healthy") await upsertAlert(client,{organizationId,locationId,type:calculated.riskLevel==='urgent'?'urgent_shortage':calculated.riskLevel==='shortage'?'projected_shortage':'low_stock',severity:calculated.riskLevel==='urgent'?'critical':'warning',title:`${item.name}: ${calculated.riskLevel.replace('_',' ')}`,summary:`Available ${Number(item.available).toFixed(2)}; recommended additional ${calculated.recommendedQuantity.toFixed(2)}.`,sourceId:item.id,details:{snapshotId:snapshot.id,shortageDate:forecastDate(asOf,calculated.shortageOffset)}});
      if (Number(exp.quantity)>0) await upsertAlert(client,{organizationId,locationId,type:"expiration_risk",severity:"warning",title:`${item.name}: expiration risk`,summary:`${Number(exp.quantity).toFixed(2)} base units expire within the forecast horizon.`,sourceId:item.id,details:{snapshotId:snapshot.id,quantity:Number(exp.quantity)}});
    }
    await client.query(`insert into forecast_category_results(snapshot_id,organization_id,pantry_location_id,inventory_category_id,available_service_units,demand_service_units,coverage_days,recommended_service_units,mapping_coverage_percent,confidence_score,risk_level,item_composition) select $1,$2,$3,c.id,coalesce(sum(fr.available_quantity/e.base_quantity_per_service_unit),0),coalesce(sum(fr.weighted_daily_demand/e.base_quantity_per_service_unit),0),case when sum(fr.weighted_daily_demand/e.base_quantity_per_service_unit)>0 then sum(fr.available_quantity/e.base_quantity_per_service_unit)/sum(fr.weighted_daily_demand/e.base_quantity_per_service_unit) end,coalesce(sum(fr.recommended_quantity/e.base_quantity_per_service_unit),0),case when count(i.id)>0 then count(e.id)::numeric/count(i.id)*100 else 0 end,coalesce(round(avg(fr.confidence_score)),0),case when bool_or(fr.risk_level='urgent') then 'urgent'::forecast_risk_level when bool_or(fr.risk_level='shortage') then 'shortage'::forecast_risk_level when bool_or(fr.risk_level='watch') then 'watch'::forecast_risk_level else 'healthy'::forecast_risk_level end,jsonb_agg(jsonb_build_object('itemId',i.id,'name',i.name,'factor',e.base_quantity_per_service_unit,'available',fr.available_quantity)) filter(where fr.id is not null) from inventory_categories c join inventory_items i on i.category_id=c.id and i.archived_at is null left join category_item_equivalencies e on e.inventory_item_id=i.id and e.inventory_category_id=c.id and e.is_active and e.archived_at is null left join forecast_item_results fr on fr.snapshot_id=$1 and fr.inventory_item_id=i.id where c.organization_id=$2 and c.archived_at is null group by c.id`,[snapshot.id,organizationId,locationId]);
    await client.query(`insert into forecast_diagnostics(snapshot_id,organization_id,pantry_location_id,inventory_category_id,code,severity,message,details) select $1,$2,$3,c.id,'MISSING_CATEGORY_EQUIVALENCY','warning','One or more category items lack a service-unit equivalency.',jsonb_build_object('missingItems',count(*)) from inventory_categories c join inventory_items i on i.category_id=c.id and i.archived_at is null left join category_item_equivalencies e on e.inventory_item_id=i.id and e.inventory_category_id=c.id and e.is_active and e.archived_at is null where c.organization_id=$2 and c.archived_at is null and e.id is null group by c.id`,[snapshot.id,organizationId,locationId]);
    const recommendations=await client.query(`select jsonb_agg(jsonb_build_object('itemId',r.inventory_item_id,'itemName',i.name,'recommendedBaseQuantity',r.recommended_quantity,'risk',r.risk_level,'neededBy',r.projected_shortage_date) order by r.risk_level desc,r.recommended_quantity desc) value from forecast_item_results r join inventory_items i on i.id=r.inventory_item_id where r.snapshot_id=$1 and r.recommended_quantity>0`,[snapshot.id]);
    await client.query(`insert into donation_need_snapshots(forecast_snapshot_id,organization_id,pantry_location_id,recommendations,generated_by) values($1,$2,$3,coalesce($4::jsonb,'[]'::jsonb),$5)`,[snapshot.id,organizationId,locationId,JSON.stringify(recommendations.rows[0]?.value ?? []),actorId]);
     await writeAudit(client,actorId,organizationId,"forecast.generated","forecast_snapshot",snapshot.id,locationId,requestId,{calculationVersion:useAdvancedModel ? "v2-hybrid-seasonal-causal" : "v1-deterministic",advancedModel:useAdvancedModel});
    await client.query("commit");
    return snapshot;
  } catch(error) { await client.query("rollback"); throw error; } finally { client.release(); }
}

export async function queueForecast(actorId:string,organizationId:string,locationId:string,requestId:string) {
  void requestId;
  await requireLocation(actorId,locationId,"forecast.recalculate");
  const key=`manual:${new Date().toISOString().slice(0,13)}`;
  const result=await pool.query(`insert into forecast_jobs(organization_id,pantry_location_id,job_type,deduplication_key,requested_by) values($1,$2,'incremental',$3,$4) on conflict(organization_id,pantry_location_id,deduplication_key) where status in('queued','running') do update set requested_at=forecast_jobs.requested_at returning *`,[organizationId,locationId,key,actorId]);
  return result.rows[0];
}

export async function processForecastJob(jobId:string) {
  const claimed=await pool.query(`update forecast_jobs set status='running',started_at=now(),attempt_count=attempt_count+1 where id=$1 and status in('queued','failed') returning *`,[jobId]);
  const job=claimed.rows[0]; if(!job) return null;
  try { const snapshot=await generateForecast(job.requested_by,job.organization_id,job.pantry_location_id,crypto.randomUUID(),job.id); await pool.query(`update forecast_jobs set status='succeeded',finished_at=now(),snapshot_id=$2,error_code=null,error_message=null where id=$1`,[job.id,snapshot.id]); return snapshot; }
  catch(error) { await pool.query(`update forecast_jobs set status='failed',finished_at=now(),error_code='FORECAST_FAILED',error_message=$2 where id=$1`,[job.id,error instanceof Error?error.message:"Unknown error"]); throw error; }
}

export async function transitionAlert(actorId:string,organizationId:string,locationId:string,alertId:string,target:"acknowledged"|"resolved"|"dismissed"|"open",reason:string,requestId:string) {
  await requireLocation(actorId,locationId,target==="acknowledged"?"alert.acknowledge":"alert.manage");
  if(target==="dismissed" && reason.trim().length<3) throw new DomainError("REASON_REQUIRED");
  const client=await pool.connect(); try { await client.query("begin"); const current=await client.query(`select * from operational_alerts where id=$1 and organization_id=$2 and pantry_location_id=$3 for update`,[alertId,organizationId,locationId]); if(!current.rows[0]) throw new DomainError("ALERT_NOT_FOUND");
    const row=current.rows[0]; await client.query(`update operational_alerts set status=$2::operational_alert_status,acknowledged_at=case when $2::text='acknowledged' then now() else acknowledged_at end,acknowledged_by=case when $2::text='acknowledged' then $3::uuid else acknowledged_by end,resolved_at=case when $2::text='resolved' then now() else null end,resolved_by=case when $2::text='resolved' then $3::uuid else null end,dismissed_at=case when $2::text='dismissed' then now() else null end,dismissed_by=case when $2::text='dismissed' then $3::uuid else null end,dismissal_reason=case when $2::text='dismissed' then $4::text else null end,updated_at=now() where id=$1`,[alertId,target,actorId,reason]); await client.query(`insert into operational_alert_events(operational_alert_id,organization_id,event_type,from_status,to_status,reason,actor_user_id) values($1,$2,'status_changed',$3,$4,$5,$6)`,[alertId,organizationId,row.status,target,reason,actorId]); await writeAudit(client,actorId,organizationId,`alert.${target}`,"operational_alert",alertId,locationId,requestId,{reason}); await client.query("commit"); return {id:alertId,status:target};
  } catch(error){await client.query("rollback");throw error;} finally{client.release();}
}

export async function updateLocationForecastConfiguration(actorId:string,organizationId:string,locationId:string,values:{weight7:number;weight30:number;weight90:number;safetyStockDays:number;leadTimeDays:number;horizonDays:number},requestId:string){
  await requireLocation(actorId,locationId,"forecast.configure");
  if([values.weight7,values.weight30,values.weight90,values.safetyStockDays,values.leadTimeDays,values.horizonDays].some(value=>!Number.isFinite(value)||value<0)||values.weight7+values.weight30+values.weight90<=0||values.horizonDays<1||values.horizonDays>365)throw new DomainError("FORECAST_CONFIGURATION_INVALID");
  const client=await pool.connect();
  try{await client.query("begin");const previous=await client.query(`select * from forecast_configurations where organization_id=$1 and pantry_location_id=$2 and scope_type='location_default' and is_active and archived_at is null for update`,[organizationId,locationId]);if(previous.rows[0])await client.query(`update forecast_configurations set is_active=false,archived_at=now() where id=$1`,[previous.rows[0].id]);const inserted=await client.query(`insert into forecast_configurations(organization_id,pantry_location_id,scope_type,lookback_7_day_weight,lookback_30_day_weight,lookback_90_day_weight,safety_stock_days,lead_time_days,forecast_horizon_days,created_by) values($1,$2,'location_default',$3,$4,$5,$6,$7,$8,$9) returning *`,[organizationId,locationId,values.weight7,values.weight30,values.weight90,values.safetyStockDays,values.leadTimeDays,values.horizonDays,actorId]);await writeAudit(client,actorId,organizationId,"forecast.configuration_updated","forecast_configuration",inserted.rows[0].id,locationId,requestId,{previousId:previous.rows[0]?.id??null});await client.query("commit");return inserted.rows[0];}catch(error){await client.query("rollback");throw error;}finally{client.release();}
}
