import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { sendIndividualMessageAction } from "@/domains/messaging/actions";
import { listMessagingContacts } from "@/domains/messaging/queries";
import { maskPhoneNumber } from "@/domains/messaging/policy";
import { previewIndividualMessage } from "@/domains/messaging/service";
import { can, requireOrganizationContext } from "@/lib/auth/access";

export default async function IndividualMessagePage({ params, searchParams }: { params: Promise<{ organizationSlug: string }>; searchParams: Promise<{ contactId?: string; body?: string; language?: string; scheduledFor?: string }> }) {
  const { organizationSlug } = await params; const search = await searchParams; const context = await requireOrganizationContext(organizationSlug); const location = context.activeLocation;
  if (!location || !can(context.effectivePermissions, "message.send_individual")) notFound();
  const organizationId = context.access.organization.id; const contacts = await listMessagingContacts(context.user.id, organizationId, location.id);
  let preview: Awaited<ReturnType<typeof previewIndividualMessage>> | null = null;
  if (search.contactId && search.body) try { preview = await previewIndividualMessage(context.user.id, organizationId, location.id, { contactId: search.contactId, body: search.body, language: search.language || "en", idempotencyKey: crypto.randomUUID(), scheduledFor: search.scheduledFor ? new Date(search.scheduledFor) : null }); } catch { preview = null; }
  return <div className="grid gap-10"><PageHeader eyebrow="Explicit confirmation required" title="Individual message" description="Choose a contact and review the exact body, masked number, consent result, segment count, provider mode, and schedule before confirming." />
    <form method="get" className="grid gap-4 border border-[var(--rule)] bg-white p-5 md:grid-cols-2"><SelectField label="Household contact" name="contactId" defaultValue={search.contactId} required><option value="">Select a contact</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.display_name} · {contact.name} · {maskPhoneNumber(contact.phone_normalized)} · {contact.consent_status ?? "no consent"}</option>)}</SelectField><Field label="Language" name="language" defaultValue={search.language || "en"}/><TextAreaField label="Message" name="body" defaultValue={search.body} required maxLength={1600} className="md:col-span-2"/><Field label="Schedule (optional)" name="scheduledFor" type="datetime-local" defaultValue={search.scheduledFor}/><button className="min-h-11 self-end border border-[var(--ink)] px-4 py-2 font-semibold" type="submit">Review message</button></form>
    {preview ? <section className="border border-[var(--ink)] bg-white p-5"><h2 className="text-xl font-semibold">Confirm exact send</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-[var(--muted)]">Recipient</dt><dd>{preview.recipient.display_name} · {preview.recipient.contact_name}</dd></div><div><dt className="text-[var(--muted)]">Phone</dt><dd>{maskPhoneNumber(preview.eligibility.normalizedPhoneNumber)}</dd></div><div><dt className="text-[var(--muted)]">Consent</dt><dd>{preview.eligibility.eligible ? "Eligible now" : `Excluded: ${preview.eligibility.exclusionReason}`}</dd></div><div><dt className="text-[var(--muted)]">Message size</dt><dd>{preview.characters} characters · {preview.segments} segment(s) · {preview.encoding}</dd></div></dl><p className="mt-5 whitespace-pre-wrap border-l-4 border-[var(--rule)] pl-4">{preview.body}</p>{preview.eligibility.eligible ? <ActionForm action={sendIndividualMessageAction.bind(null, organizationId, organizationSlug, location.id)} className="mt-5 grid gap-4"><input type="hidden" name="contactId" value={search.contactId}/><input type="hidden" name="body" value={search.body}/><input type="hidden" name="language" value={search.language || "en"}/><input type="hidden" name="scheduledFor" value={search.scheduledFor || ""}/><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><label className="flex items-start gap-3 text-sm font-medium"><input type="checkbox" name="confirmed" value="yes" required/>I confirm this recipient, message, provider mode, and schedule.</label><SubmitButton pendingLabel="Processing…">Confirm message</SubmitButton></ActionForm> : <p className="mt-5 text-sm text-[var(--signal)]">This recipient is not eligible. No message can be sent.</p>}</section> : null}
  </div>;
}
