import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { createDonationAction, createPurchasedShipmentAction, startReceivingAction } from "@/domains/inventory/operations-actions";
import { listDonations, listDonors, listOperationalChoices, listReceivingSessions } from "@/domains/inventory/operations-queries";

export default async function ReceivingPage({ params }: { params: Promise<{ organizationSlug: string }> }) {
  const { organizationSlug } = await params; const context = await requireOrganizationContext(organizationSlug);
  if (!can(context.effectivePermissions, "receiving.view")) notFound(); const location = context.activeLocation;
  if (!location) return <PageHeader eyebrow="Inventory operations" title="Receiving" description="Select an active pantry location to receive stock." />;
  const organizationId = context.access.organization.id;
  const [sessions, donations, donors, choices] = await Promise.all([listReceivingSessions(organizationId, location.id), listDonations(organizationId, location.id), listDonors(organizationId), listOperationalChoices(organizationId, location.id)]);
  const mayCreate = can(context.effectivePermissions, "receiving.create");
  return <div className="grid gap-10"><PageHeader eyebrow="Inventory operations" title={`Receiving · ${location.name}`} description="Donation and purchase intake posts to the immutable lot ledger only when a session is completed." />
    <section className="overflow-x-auto border bg-white"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b bg-[var(--surface)] text-left"><th className="p-3">Session</th><th className="p-3">Source</th><th className="p-3">Lines</th><th className="p-3">Status</th><th className="p-3">Started</th></tr></thead><tbody>{sessions.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="p-3"><Link className="font-semibold underline" href={`/app/${organizationSlug}/inventory/receiving/${row.id}`}>{row.id.slice(0, 8)}</Link></td><td className="p-3">{row.donation_number ?? row.supplier_name ?? row.source_type}</td><td className="p-3">{row.line_count}</td><td className="p-3">{row.status.replaceAll("_", " ")}</td><td className="p-3">{new Date(row.started_at).toLocaleString()}</td></tr>)}</tbody></table></section>
    {mayCreate ? <section className="grid gap-6 xl:grid-cols-3"><article className="border bg-white p-6"><h2 className="text-xl font-semibold">Create donation intake</h2><ActionForm action={createDonationAction.bind(null, organizationId, organizationSlug, location.id)} className="mt-4 grid gap-4"><Field label="Donation number" name="donationNumber" required placeholder={`DON-${new Date().getFullYear()}-`} /><SelectField label="Donor" name="donorId"><option value="">Anonymous donor</option>{donors.filter((d) => d.status === "active").map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</SelectField><Field label="Donation date" name="donationDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /><SelectField label="Expected item (optional)" name="itemId"><option value="">Add during receiving</option>{choices.items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><Field label="Expected quantity" name="expectedQuantity" inputMode="decimal" /><SelectField label="Expected unit" name="unitId"><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><TextAreaField label="Notes" name="notes" /><SubmitButton>Create intake</SubmitButton></ActionForm></article>
      <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Create purchase receipt</h2><ActionForm action={createPurchasedShipmentAction.bind(null, organizationId, organizationSlug, location.id)} className="mt-4 grid gap-4"><Field label="Supplier name" name="supplierName" required /><Field label="Supplier reference" name="supplierReference" /><TextAreaField label="Purchase notes" name="notes" /><SubmitButton>Create purchase</SubmitButton></ActionForm></article>
      <article className="border bg-white p-6"><h2 className="text-xl font-semibold">Start receiving</h2><ActionForm action={startReceivingAction.bind(null, organizationId, organizationSlug, location.id)} className="mt-4 grid gap-4"><SelectField label="Source" name="sourceType" defaultValue="donation"><option value="donation">Donation intake</option><option value="purchase">Purchased shipment</option><option value="other">Other receipt</option></SelectField><SelectField label="Donation" name="donationId"><option value="">Not linked</option>{donations.filter((d) => !["completed", "cancelled"].includes(d.status)).map((d) => <option key={d.id} value={d.id}>{d.donation_number} · {d.donor_name}</option>)}</SelectField><SelectField label="Purchased shipment" name="purchasedShipmentId"><option value="">Not linked</option>{choices.purchases.map((p) => <option key={p.id} value={p.id}>{p.supplier_name}{p.supplier_reference ? ` · ${p.supplier_reference}` : ""}</option>)}</SelectField><TextAreaField label="Session notes" name="notes" /><SubmitButton>Start session</SubmitButton></ActionForm></article></section> : null}
  </div>;
}
