import { notFound } from "next/navigation";
import { ActionForm } from "@/components/ui/action-form";
import { Field, SelectField, TextAreaField } from "@/components/ui/field";
import { PageHeader } from "@/components/ui/page-header";
import { SubmitButton } from "@/components/ui/submit-button";
import { can, requireOrganizationContext } from "@/lib/auth/access";
import { addReceivingLineAction, cancelReceivingAction, completeReceivingAction } from "@/domains/inventory/operations-actions";
import { getReceivingSession, listOperationalChoices } from "@/domains/inventory/operations-queries";

export default async function ReceivingDetailPage({ params }: { params: Promise<{ organizationSlug: string; sessionId: string }> }) {
  const { organizationSlug, sessionId } = await params; const context = await requireOrganizationContext(organizationSlug); if (!can(context.effectivePermissions, "receiving.view")) notFound();
  const organizationId = context.access.organization.id; const result = await getReceivingSession(organizationId, sessionId); if (!result) notFound();
  const session = result.session as Record<string, unknown>; const locationId = String(session.pantry_location_id); const choices = await listOperationalChoices(organizationId, locationId); const open = ["draft", "in_progress", "review"].includes(String(session.status));
  return <div className="grid gap-10"><PageHeader eyebrow="Receiving session" title={`Session ${sessionId.slice(0, 8)}`} description={`${String(session.source_type)} · ${String(session.status).replaceAll("_", " ")}`} />
    <section className="overflow-x-auto border bg-white"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b bg-[var(--surface)] text-left"><th className="p-3">Item</th><th className="p-3">Quantity</th><th className="p-3">Lot</th><th className="p-3">Dates</th><th className="p-3">Status</th></tr></thead><tbody>{result.lines.map((line) => <tr key={String(line.id)} className="border-b last:border-0"><td className="p-3 font-semibold">{String(line.item_name)}</td><td className="p-3">{String(line.entered_quantity)} {String(line.entered_unit)}</td><td className="p-3">{line.lot_number ? String(line.lot_number) : "new lot"}</td><td className="p-3">received {String(line.received_date)}{line.expiration_date ? ` · expires ${String(line.expiration_date)}` : ""}</td><td className="p-3">{String(line.line_status)}</td></tr>)}</tbody></table></section>
    {open && can(context.effectivePermissions, "receiving.create") ? <section className="border bg-white p-6"><h2 className="text-xl font-semibold">Add line</h2><ActionForm action={addReceivingLineAction.bind(null, organizationId, organizationSlug, sessionId)} className="mt-4 grid gap-4 md:grid-cols-2"><SelectField label="Item" name="itemId" required><option value="">Select item</option>{choices.items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Existing lot (optional)" name="existingLotId"><option value="">Create a new lot</option>{choices.lots.map((l) => <option key={l.id} value={l.id}>{l.item_name} · {l.lot_code ?? "unlabeled"}</option>)}</SelectField><Field label="Quantity" name="quantity" required inputMode="decimal" /><SelectField label="Unit" name="unitId" required><option value="">Select unit</option>{choices.items.map((i) => <option key={i.id} value={i.base_unit_id}>{i.name} · {i.base_unit}</option>)}</SelectField><Field label="Lot number" name="lotNumber" /><Field label="Received date" name="receivedDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /><Field label="Best-by date" name="bestByDate" type="date" /><Field label="Expiration date" name="expirationDate" type="date" /><TextAreaField label="Notes" name="notes" className="md:col-span-2" /><SubmitButton>Add receiving line</SubmitButton></ActionForm></section> : null}
    {open ? <section className="grid gap-4 md:grid-cols-2">{can(context.effectivePermissions, "receiving.complete") ? <ActionForm action={completeReceivingAction.bind(null, organizationId, organizationSlug, sessionId)} className="border bg-white p-6"><p className="mb-4 text-sm text-[var(--muted)]">Completion validates every line and posts all inventory atomically.</p><SubmitButton>Complete and post inventory</SubmitButton></ActionForm> : null}{can(context.effectivePermissions, "receiving.cancel") ? <ActionForm action={cancelReceivingAction.bind(null, organizationId, organizationSlug, sessionId)} className="border bg-white p-6"><Field label="Cancellation reason" name="reason" required /><SubmitButton>Cancel session</SubmitButton></ActionForm> : null}</section> : null}
  </div>;
}
